export const apiUrl = 'http://localhost:3456/rest'

export const REQUEST_LOGIN_ACCOUNT = 'REQUEST_LOGIN_ACCOUNT'
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS'
export const LOGIN_ACCOUNT_FAIL = 'LOGIN_ACCOUNT_FAIL'

export const REQUEST_REGISTER_USER = 'REQUEST_ADD_USER'
export const REGISTER_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'ADD_USER_FAIL'