// css
export const bootstrapMode1 = 'col-lg-3 mt-3'
export const bootstrapMode2 = 'col-lg-4 col-md-6 col-sm-10 offset-md-0 offset-sm-1'

// api
export const apiUrl = 'http://localhost:3456/rest'


// user
export const REQUEST_LOGIN_ACCOUNT = 'REQUEST_LOGIN_ACCOUNT'
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS'
export const LOGIN_ACCOUNT_FAIL = 'LOGIN_ACCOUNT_FAIL'


export const REQUEST_GET_PRODUCTS = 'REQUEST_GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'

export const REQUEST_GET_USER_TOKEN = 'REQUEST_GET_USER_TOKEN'
export const GET_USER_TOKEN_SUCCESS = 'GET_USER_TOKEN_SUCCESS'
export const GET_USER_TOKEN_FAIL = 'GET_USER_TOKEN_FAIL'

export const REQUEST_ADD_EMPLOYEE = 'REQUEST_ADD_EMPLOYEE'
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS'
export const ADD_EMPLOYEE_FAIL = 'ADD_EMPLOYEE_FAIL'


export const REQUEST_CHANGE_STATUS = 'REQUEST_CHANGE_STATUS'
export const CHANGE_STATUS_SUCCESS = 'CHANGE_STATUS_SUCCESS'
export const CHANGE_STATUS_FAIL = 'RCHANGE_STATUS_FAIL'

export const REQUEST_EDIT_EMPLOYEE = 'REQUEST_EDIT_EMPLOYEE'
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS'
export const EDIT_EMPLOYEE_FAIL = 'EDIT_EMPLOYEE_FAIL'

export const REQUEST_GET_USER_BY_ID = 'REQUEST_GET_USER_ID'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_BY_ID_FAIL = 'GET_USER_BY_ID_FAIL'


export const REQUEST_GET_ALL_USERS = 'REQUEST_GET_ALL_USERS'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL'

export const REQUEST_ADD_USER = 'REQUEST_ADD_USER'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'

export const REQUEST_EDIT_USER = 'REQUEST_EDIT_USER'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL'


// product
export const REQUEST_EDIT_PRODUCT = 'REQUEST_EDIT_PRODUCT'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_SUCCESS'

export const REQUEST_GET_PRODUCT_BY_ID = 'REQUEST_GET_PRODUCT_BY_ID'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCT_BY_ID_FAIL = 'GET_PRODUCT_BY_ID_FAIL'

export const REQUEST_ADD_PRODUCT = 'REQUEST_ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL'

export const REQUEST_DELETE_PRODUCT = 'REQUEST_DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

export const REQUEST_SEARCH_PRODUCT = 'REQUEST_SEARCH_PRODUCT'
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS'
export const SEARCH_PRODUCT_FAIL = 'SEARCH_PRODUCT_FAIL'
